/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { z } from 'genkit';
import { ai } from './genkit.js';

export const InputQuestionSchema = ai.defineSchema(
  'InputQuestionSchema',
  z.object({
    question: z.string().describe("The user's financial question or topic"),
  }).describe("Input Question Schema")
);

export const MammaAdviceSchema = ai.defineSchema(
  'MammaAdviceSchema',
  z.object({
    response: z.string().describe("Mamma's financial advice"),
    mammaApprovalRating: z.number().min(1).max(10).describe("Mamma's approval rating from 1 to 10"),
    imageData: z.string().optional().describe("Optional base64-encoded image data generated by Mamma."),
  }).describe("Mamma's structured financial advice")
);

export const CritiqueSchema = ai.defineSchema(
  'CritiqueSchema',
  z.object({
    requiresRevision: z.boolean().describe("True if the advice can be improved, false otherwise."),
    critique: z.string().describe("Specific suggestions for improving the advice. Empty if no revision is needed."),
  })
);
